### ISSUE TITLE
When updating to new version, the menu is destroyed

### ISSUE THREAD

**Issue by steve6375** [nguyentumine/AIO-Boot#8] opened 2016-09-18 10:49 UTC
if I update to a new version, the main.cfg files, etc. are destroyed.
Have you seen the script that I use for Easy2Boot Grub2?
It has a script in main.cfg and other files which searches for .cfg files ( .grub2 = .cfg files) and incorporates them into the menu.
This means that you can update to a new version and any existing menu files will automatically be included.
# ######## GET MENU FILES

set isofpath=${isofpath}/MAINMENU
set isopath=${isopath}/MAINMENU
set ip=$isopath ; set ifp=$isofpath
echo Looking for .grub2 files in $isopath...
for cfg_file in $isofpath/grub2/*.grub2; do
    echo "Found $cfg_file"
    source $cfg_file
    set fnd=1
done
unset fnd
# ##### END OF MENU COLLECTING

**Comment by nguyentumine** [comment] 2016-09-18 11:28
Only **main.cfg** file will be overridden, but this has been fixed in the latest version through your reminders, thank so much!

I also had wanted to scan the configuration files and use them but I think it will be slower. I will refer your tool to improve my tool is better. Thank again!

[AIOBoot-v0.9.0.1b6.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiY3VrVXNpaGpXSGc/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-18 12:36
P.S. I just found out that secure boot prevents some scripts from working!
e.g. ls will not work (**error: Secure Boot forbids loading module from (hd0,msdos1)/boot/grub/x86_64.efi/ls.mod**)
and some other things dont work like  **for xxx in /_ISO/MAINMENU ; do**  loops

strangely,  
**if [ -e "/path/file" ] ; then xxxxx**
lines do work!

**Comment by nguyentumine** [comment] 2016-09-18 13:26
I noticed that your Grub2 (Boot folder) only be loaded in the first partition, while the Grub2 folder (like AIO & Boot...) can put on any partition... Why not build your own **boot.img** and **core.img**?
[https://www.youtube.com/watch?v=FCXqL-SmWT0](https://www.youtube.com/watch?v=FCXqL-SmWT0)
[https://www.youtube.com/watch?v=G5_0-956peE](https://www.youtube.com/watch?v=G5_0-956peE)

**ls** command is working, check it [http://prnt.sc/cjet9v](http://prnt.sc/cjet9v)

**Comment by steve6375** [comment] 2016-09-18 13:39
Thanks for Ytube links.
re. ls command - when you secure boot, grub2 cannot load modules - did you test with secure boot?

**Comment by nguyentumine** [comment] 2016-09-18 15:21
Sorry, my computer does not have this feature

**Comment by steve6375** [comment] 2016-09-18 16:14
I know, I am just saying that maybe using scripting for auto-detection of .cfg files is maybe not so good for your AIOBoot because it stops secure boot from working. Under Secure Boot, you cannot access other drives or reference a partition (e.g. hd0,msdos1) or load .mod modules because it does not allow it. This means lots of scripting does not seem to work!

**Comment by nguyentumine** [comment] 2016-09-18 21:59
Try to pre-load modules as you need, all files will be embedded in bootx64.efi...

**Comment by steve6375** [comment] 2016-09-18 22:29
Thanks, I am trying that for hours (!) but make gives an error about kernel.h missing
http://twobit.us/2015/09/building-and-booting-grub2-for-uefi-system/
I use grub 2.02 Beta 3 on Mint
./autogen.sh
./configure --target=x86_64 --with-platform=efi
make

**Comment by steve6375** [comment] 2016-09-18 22:32
![image](https://cloud.githubusercontent.com/assets/1469350/18619583/2bf81158-7df8-11e6-8cdf-62f7dfe8ed0e.png)

**Comment by nguyentumine** [comment] 2016-09-18 22:43
I just use the packages provided in the repository, using command
`sudo apt install grub-efi-ia32-bin grub-efi-amd64-bin grub-pc-bin grub2-common grub-efi-amd64-signed`
It works on Ubuntu and also work on Mint

**Comment by steve6375** [comment] 2016-09-18 23:50
I still get same error! I assume you mean grub-efi-amd64 and not grub-efi-ia32...?
Any other suggestions please?

**Comment by nguyentumine** [comment] 2016-09-18 23:57
Both **grub-efi-ia32-bin** and **grub-efi-amd64-bin**, this means Grub2 will support installed on both UEFI IA32 and x64 platforms
[grub-efi-amd64-bin](https://community.linuxmint.com/software/view/grub-efi-amd64-bin)
[grub-efi-ia32-bin](https://community.linuxmint.com/software/view/grub-efi-ia32-bin)

I'm not sure on Mint but it worked on Ubuntu

I've embedded all modules into **grubx64.efi** file, please help me check it, just replace **/EFI/Boot/grubx64.efi**

Thank you!

**Comment by steve6375** [comment] 2016-09-19 00:03
your grubx64.efi is not booting in non-secure mode as bootx64.efi ??? DId you try it

**Comment by steve6375** [comment] 2016-09-19 00:05
What grub.cfg does it look for?

**Comment by nguyentumine** [comment] 2016-09-19 00:07
Bootx64.efi =Shimx64.efi
PC boot Bootx64.efi (Shimx64.efi) -> grubx64.efi ->search root and prefix -> load grub.cfg

**Comment by steve6375** [comment] 2016-09-19 00:12
Does it have fat module? I cannot access (hd0,msdos1) ??

**Comment by nguyentumine** [comment] 2016-09-19 00:14
Here is the list of modules

'acpi' 'adler32' 'affs' 'afs' 'ahci' 'all_video' 'aout' 'appleldr' 'archelp' 'ata' 'at_keyboard' 'backtrace' 'bfs' 'bitmap' 'bitmap_scale' 'blocklist' 'boot' 'bsd' 'bswap_test' 'btrfs' 'bufio' 'cat' 'cbfs' 'cbls' 'cbmemc' 'cbtable' 'cbtime' 'chain' 'cmdline_cat_test' 'cmp' 'cmp_test' 'configfile' 'cpio_be' 'cpio' 'cpuid' 'crc64' 'cryptodisk' 'crypto' 'cs5536' 'ctz_test' 'datehook' 'date' 'datetime' 'diskfilter' 'disk' 'div' 'div_test' 'dm_nv' 'echo' 'efifwsetup' 'efi_gop' 'efinet' 'efi_uga' 'ehci' 'elf' 'eval' 'exfat' 'exfctest' 'ext2' 'extcmd' 'fat' 'file' 'fixvideo' 'font' 'fshelp' 'functional_test' 'gcry_arcfour' 'gcry_blowfish' 'gcry_camellia' 'gcry_cast5' 'gcry_crc' 'gcry_des' 'gcry_dsa' 'gcry_idea' 'gcry_md4' 'gcry_md5' 'gcry_rfc2268' 'gcry_rijndael' 'gcry_rmd160' 'gcry_rsa' 'gcry_seed' 'gcry_serpent' 'gcry_sha1' 'gcry_sha256' 'gcry_sha512' 'gcry_tiger' 'gcry_twofish' 'gcry_whirlpool' 'geli' 'gettext' 'gfxmenu' 'gfxterm_background' 'gfxterm_menu' 'gfxterm' 'gptsync' 'gzio' 'halt' 'hashsum' 'hdparm' 'hello' 'help' 'hexdump' 'hfs' 'hfspluscomp' 'hfsplus' 'http' 'iorw' 'iso9660' 'jfs' 'jpeg' 'keylayouts' 'keystatus' 'ldm' 'legacycfg' 'legacy_password_test' 'linux16' 'linux' 'loadbios' 'loadenv' 'loopback' 'lsacpi' 'lsefimmap' 'lsefi' 'lsefisystab' 'lsmmap' 'ls' 'lspci' 'lssal' 'luks' 'lvm' 'lzopio' 'macbless' 'macho' 'mdraid09_be' 'mdraid09' 'mdraid1x' 'memdisk' 'memrw' 'minicmd' 'minix2_be' 'minix2' 'minix3_be' 'minix3' 'minix_be' 'minix' 'mmap' 'morse' 'mpi' 'msdospart' 'mul_test' 'multiboot2' 'multiboot' 'nativedisk' 'net' 'newc' 'nilfs2' 'normal' 'ntfscomp' 'ntfs' 'odc' 'offsetio' 'ohci' 'part_acorn' 'part_amiga' 'part_apple' 'part_bsd' 'part_dfly' 'part_dvh' 'part_gpt' 'part_msdos' 'part_plan' 'part_sun' 'part_sunpc' 'parttool' 'password' 'password_pbkdf2' 'pata' 'pbkdf2' 'pbkdf2_test' 'pcidump' 'play' 'png' 'priority_queue' 'probe' 'procfs' 'progress' 'raid5rec' 'raid6rec' 'random' 'read' 'reboot' 'regexp' 'reiserfs' 'relocator' 'romfs' 'scsi' 'search_fs_file' 'search_fs_uuid' 'search_label' 'search' 'serial' 'setjmp' 'setjmp_test' 'setpci' 'sfs' 'shift_test' 'signature_test' 'sleep' 'sleep_test' 'spkmodem' 'squash4' 'syslinuxcfg' 'tar' 'terminal' 'terminfo' 'test_blockarg' 'testload' 'test' 'testspeed' 'tftp' 'tga' 'time' 'trig' 'tr' 'true' 'udf' 'ufs1_be' 'ufs1' 'ufs2' 'uhci' 'usb_keyboard' 'usb' 'usbms' 'usbserial_common' 'usbserial_ftdi' 'usbserial_pl2303' 'usbserial_usbdebug' 'usbtest' 'verify' 'video_bochs' 'video_cirrus' 'video_colors' 'video_fb' 'videoinfo' 'video' 'videotest_checksum' 'videotest' 'xfs' 'xnu' 'xnu_uuid' 'xnu_uuid_test' 'xzio' 'zfscrypt' 'zfsinfo' 'zfs'

**Comment by steve6375** [comment] 2016-09-19 00:18
biosdisk ? is that needed?
I have a FAT32 USb under VBox with a /grub.cfg and /AIO/grub.cfg.
I just get grub> prompt??

**Comment by nguyentumine** [comment] 2016-09-19 00:21
biosdisk only support for BIOS, not UEFI

I don't know why it did not work
This is the file that only embed **ls.mod**, try ls command
[grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiWlhLMG9Tc1U5aTQ/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-19 00:27
yes, ls works and I can see (hd0,msdos1) with that version.

**Comment by nguyentumine** [comment] 2016-09-19 00:28
Thank you, I will remove unnecessary modules, I think there is an incompatibility between the modules

**Comment by steve6375** [comment] 2016-09-19 00:33
I require modules:
biosdisk part_msdos fat ntfs exfat
ls echo cpuid loopback regexp read bsd probe
ext2

**Comment by steve6375** [comment] 2016-09-19 00:37
If I use your first large file grubx64.efi as bootx64.efi on real system, it gives message:
error: variable 'prefix' isn't set.

but under VBox, it just goes to grub> shell

**Comment by nguyentumine** [comment] 2016-09-19 00:39
Please turn on the UEFI mode in VirtualBox and try reinstalling Grub2
On Ubuntu, I was always successful when using this command:

`sudo apt install grub-efi-ia32-bin grub-efi-amd64-bin grub-pc-bin grub2-common grub-efi-amd64-signed`

Perhaps there are too many modules have prevented it working properly.

**Comment by steve6375** [comment] 2016-09-19 00:44
![image](https://cloud.githubusercontent.com/assets/1469350/18620435/55344be2-7e0a-11e6-947b-036a9a70aecd.png)

If I use ls version, then I can see (hd0,msdos1), but if I use original large version then no (hd0,msdos1) or other drives accessible. I think it is too large. Maybe compile less modules.

**Comment by steve6375** [comment] 2016-09-19 00:47
![image](https://cloud.githubusercontent.com/assets/1469350/18620457/fa5c01c8-7e0a-11e6-9448-4e7608a3a71c.png)

**Comment by nguyentumine** [comment] 2016-09-19 00:47
Yes, I would choose the modules needed

Try this:
`sudo apt install grub-efi-ia32-bin grub-efi-amd64-bin grub-pc-bin grub2-common`

**Comment by steve6375** [comment] 2016-09-19 00:53
That seemed to install OK, I then did
./autogen.sh
./configure --target=x86_64 --with-platform=efi
make

but same problem with kernel.h  !!!

**Comment by nguyentumine** [comment] 2016-09-19 01:02
I've embedded the modules as you want, please help me try it

`part_msdos fat ntfs exfat ls echo cpuid loopback regexp read bsd probe ext2`

[grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTicGNkTEZPTnRhUmM/view?usp=sharing)

Why do you need to build it while it is available in the repository?

**Comment by steve6375** [comment] 2016-09-19 01:08
![image](https://cloud.githubusercontent.com/assets/1469350/18620600/c9fa9ec4-7e0d-11e6-80a2-27dff4a70557.png)
better!
Can you add configfile module too please?

I need these modules so that Secure Boot + scripts will work. In Secure Boot mode, grub2 will not load any external modules for security reasons. I am hoping that  built-in modules will work.

**Comment by steve6375** [comment] 2016-09-19 01:12
According to http://twobit.us/2015/09/building-and-booting-grub2-for-uefi-system/
Since we’ve specified the prefix in the builtin config the -p option below is useless **but grub-mkimage throws an error if it’s not provided**. The value we pass is obviously wrong but the image produced will still function.

**Comment by nguyentumine** [comment] 2016-09-19 01:14
Added `configfile` module, test it on real system please
[grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiakJmby16UHV2cnM/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-19 01:18
On VBOX
![image](https://cloud.githubusercontent.com/assets/1469350/18620682/393b6dbc-7e0f-11e6-83db-a2df3b79c201.png)
Same on real system (not secure boot) - just using file as  bootx64.efi

**Comment by nguyentumine** [comment] 2016-09-19 01:23
Although still appear notice but then it worked for me...

**Comment by steve6375** [comment] 2016-09-19 01:29
If I press ENTER then it boots on VM and real system. So problem with prefix and / in path still???
but if I try to boot an ISO from menu it says 'grub-efi-secure-boot' not found about 4 times (clonezilla).

Also, I cannot secure boot when using shimx64.efi  as bootx64.efi.
If I use your original bootx64 with shimx64 from AIOBoot, then it does boot to menu in Secure Boot.
So some secure boot module is missing from your new efi file???

**Comment by steve6375** [comment] 2016-09-19 01:33
Must get zzzzzz now (2.30 AM here!). Will test more tomorrow. Thanks!

**Comment by nguyentumine** [comment] 2016-09-19 05:13
I have built Grub2 from source but the bootx64.efi still does not work

**Comment by nguyentumine** [comment] 2016-09-19 06:38
Try this, hope it works well
[UEFI-Secure-Boot.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiSjZDTVNVb18zTUE/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-19 07:32
The bootx64.efi certainly looks much better. non-secure boot looks good.
But still same problem with Secure Boot.
I get blue screen with **ERROR   Verification failed: (15) Access Denied** error

Secure Boot needs 'chain of trust' and so I guess something about .efi file is not 'signed' or correct format???

**Comment by nguyentumine** [comment] 2016-09-19 08:15
Boot directlly to bootx64.efi, dont use shimx64.efi

**Comment by steve6375** [comment] 2016-09-19 08:26
I found v detailed grub2 boot info
http://www.slideshare.net/MikeWang45/grub2-booting-process
It mentions linuxefi module (slide 29)

**Comment by steve6375** [comment] 2016-09-19 08:49
_Boot directlly to bootx64.efi, dont use shimx64.efi_ >> this will not secure boot - must use shimx64 to secure boot...

**Comment by nguyentumine** [comment] 2016-09-19 09:48
Bootx64.efi file which I've uploaded has been signed, linuxefi.mod also availabel in \AIO\grub\x86_64-efi folder

**Comment by steve6375** [comment] 2016-09-19 09:57
In secure boot, .mod files cannot be loaded. I am not sure what linuxefi.mod does???
Anyway, I cannot secure boot with the new bootx64.efi using shim.
I tried Ubuntu shim (bootx64.efi 1,289,424 bytes) and the shim you had in AIOBoot (1,293,304 bytes) - both give access denied error - if I replace grubx64.efi with original version or Ubuntu grubx64.efi, it does boot to grub2 with secure boot enabled.

**Comment by nguyentumine** [comment] 2016-09-19 10:08
[UEFI-Secure-Boot.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiSjZDTVNVb18zTUE/view?usp=sharing)

I've uploaded bootx64.efi file (1,08 MB (1.135.480 bytes)), have you tried it yet?

**Comment by steve6375** [comment] 2016-09-19 10:10
Yes, that is what I am testing with.

**Comment by nguyentumine** [comment] 2016-09-19 10:21
I took the file from the Ubuntu, in [grub-efi-amd64-signed](http://packages.ubuntu.com/xenial-updates/amd64/grub-efi-amd64-signed/filelist) package, **gcdx64.efi.signed** > **bootx64.efi**

This is the original version:
[EFI.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiMU9LQjNSZXYyOGc/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-19 10:25
OK. There is no problem with the 'official' efi file with secure boot, except that scripts dont work and you cannot load external .mod files. For scripts to work, I need various modules (cpuid, loopback, regexp, read, echo, bsd, probe, configfile, + usual fat, ext2, ntfs etc..
So what I want to try to get is signed efi with these modules inside so scripts will work.

**Comment by nguyentumine** [comment] 2016-09-19 10:29
I understand, it was everything that I get from Ubuntu, it still does not work?

**Comment by steve6375** [comment] 2016-09-19 10:31
No. Did you run some sort of sign/certificate on kernel?
I am not sure how you do this. Maybe files have to be sent away for signing otherwise any hacker could make a virus using this process+shim?

**Comment by nguyentumine** [comment] 2016-09-19 10:33
I always use the files apparently originated

http://image.prntscr.com/image/e681493046424e169803ea3473bb14fc.png

**Comment by nguyentumine** [comment] 2016-09-19 10:43
A sorry, this file signed with Canonical's UEFI signing key, not Microsoft...

**Comment by steve6375** [comment] 2016-09-19 10:46
![image](https://cloud.githubusercontent.com/assets/1469350/18629604/88ddad22-7e5e-11e6-81c7-26c2c4bc9eb3.png)
Yes - I was just about to say that. I think maybe it has to be sent to MS???
It may be possible using mok manager efi - but that is not good solution for USB booting.

**Comment by steve6375** [comment] 2016-09-19 10:52
But Ubuntu grubx64.efi has Canonical certificate and it works with secure boot + shim.

**Comment by nguyentumine** [comment] 2016-09-19 10:54
All we need to do now is to embed the module into bootx64.efi right? I will try again

**Comment by nguyentumine** [comment] 2016-09-19 10:57
The certificate that I'm referring to is the certificate to verify the source of the file, not for Secure BOOT

**Comment by steve6375** [comment] 2016-09-19 11:06
P.S. FInally got make to work (I did **make distclean** and then ran autogen+configure+make again and it worked).

**Comment by nguyentumine** [comment] 2016-09-19 11:12
To build multiple platforms:
```
./configure --with-platform=efi
./configure --target=i386 --with-platform=efi
./configure --with-platform=pc
```

**Comment by steve6375** [comment] 2016-09-19 12:00
P.S. Can you add code to search for standard \boot\grub\grub.cfg as well as AIO .cfg file and the /grub.cfg and /EFI/boot/grub.cfg so your efi file can be used by others?
maybe along these lines
search.fs_label grub root
if [ -e /boot/grub/example/test1.cfg ]; then
    set prefix=($root)/boot/grub
    configfile /boot/grub/example/test1.cfg
else
    if [ -e /boot/grub/example/test2.cfg ]; then
        set prefix=($root)/boot/grub
        configfile /boot/grub/example/test2.cfg
    else
        echo "Could not find an example configuration file!"
    fi
fi

**Comment by nguyentumine** [comment] 2016-09-19 12:08
You can embed small configuration file by using **grub-mkimage** like this
`grub-mkimage --help
grub-mkimage --config 'load.cfg'`
Put your code in **load.cfg**, ie search and set root, set prefix...
But I think others can use your files, by editing Hex code...

**Comment by steve6375** [comment] 2016-09-19 16:31
If I compile a bootx64.efi using mkimage, it works OK in non-secure boot mode, but when using shim and when i run clonezilla, I get multiple errors: error symbol 'grub_efi_secure_boot' not found.
Do I need to add a module???

**Comment by nguyentumine** [comment] 2016-09-19 22:20
**ERROR Verification failed: (15) Access Denied**
You got this error while using my latest file, where is my latest file?

I think you will get help here: [help-grub](https://lists.gnu.org/archive/html/help-grub/)

**Comment by steve6375** [comment] 2016-09-19 22:23
No - it is a BIOS\firmware error or maybe shimx64.efi error (not grub2 message).
It is because your efi file is not suitable for secure boot.

**Comment by nguyentumine** [comment] 2016-09-19 22:31
Have you created the image using a fixed root partition like (,msdos1), (hd0,msdos1)...?

I use the method of scanning files or UDID to set root partition but I've always got this error
`error: variable 'prefix' isn't set.`

**Comment by steve6375** [comment] 2016-09-19 22:35
I use  -p foobar  in mkimage command line
foobar does not exist, but I think this prevents the error message???
![image](https://cloud.githubusercontent.com/assets/1469350/18651183/a5f0c36e-7ec1-11e6-9b8b-5153fde3809d.png)

P.S. I found adding ehci module causes problems.

**Comment by steve6375** [comment] 2016-09-19 22:47
what command line do you use for grub-mkimage?
I find linuxefi mentioned, but I don't have linuxefi?
http://prosauce.org/blog/2015/10/31/booting-linux-securely
How do you add certificate?

**Comment by nguyentumine** [comment] 2016-09-19 22:52
`grub-mkimage --directory '/usr/lib/grub/x86_64-efi' --prefix **'/AIO/grub'** --output 'bootx64.efi' --format 'x86_64-efi' --compression 'auto' --config **'loadpc.cfg'** 'part_gpt' 'part_msdos' 'ext2' 'fat' 'ntfs' 'hfsplus' 'search_fs_file'`

Grub2 built from the source not have **linuxefi** and **initrdefi**, but you can use **linux** and **initrd**
Redirect linuxefi-initrdefi to linux-initrd by using this function:

`function linuxefi {
    insmod regexp
    parameters="$*"
    set allparam=""
    for param in $parameters; do
        set allparam="${allparam} ${param}"
    done
    linux $allparam
}

function initrdefi {
    insmod regexp
    parameters="$*"
    set allparam=""
    for param in $parameters; do
        set allparam="${allparam} ${param}"
    done
    initrd $allparam
}`

**Comment by steve6375** [comment] 2016-09-19 22:55
I dont understand about the functions - where do I add these lines?

**Comment by nguyentumine** [comment] 2016-09-19 23:01
The function that should be read before the **linuxefi** and **initrdefi** command is used, ie add to **grub.cfg**

I think the problem is that we just embed modules file, but it's not easy

**Comment by nguyentumine** [comment] 2016-09-19 23:11
Sorry, just use `$@` to get all parameters.

```
function linuxefi {
	linux $@
}

function initrdefi {
	initrd $@
}
```

**Comment by steve6375** [comment] 2016-09-19 23:28
OK.
But if I compile my own  grubx64.efi using grub_mkimage, I still cannot run ISOs, e.g. clonezilla
![image](https://cloud.githubusercontent.com/assets/1469350/18652281/068b8f4a-7ec9-11e6-9b97-f2d96e22bfa0.png)

but your efi file does run clonezilla, etc. So I must be missing something???

**Comment by nguyentumine** [comment] 2016-09-19 23:38
I don't know, I get these files from the Ubuntu, in [grub-efi-amd64-signed](http://packages.ubuntu.com/xenial-updates/amd64/grub-efi-amd64-signed/filelist) package, **gcdx64.efi.signed** > **bootx64.efi**

My English is not good, I think you will get help here: [help-grub](https://lists.gnu.org/archive/html/help-grub/)

**Comment by steve6375** [comment] 2016-09-19 23:55
I tried shim shim-signed.tgz - it does not work.
If I use shim+ubuntu grubx64.efi I get 'xxx has been blocked by the current security policy'.

The shimx64.efi in your AIOBoot and the Ubuntu shim both work. But your compiled grub efi does not work in secure boot mode. (see blue screen in previous post).

**Comment by steve6375** [comment] 2016-09-20 00:01
When Ubuntu shim + your latest grubx64.efi or my efi file, I see a message 'failed to load image - access denied' very quick on screen. Then I get blue screen 'Verification failed: (15) Access Denied'

**Comment by nguyentumine** [comment] 2016-09-20 00:06
Yes, I understand but I don't know how to compile large files

**Comment by nguyentumine** [comment] 2016-09-20 04:25
Try this command:
`grub-mkstandalone --help`

[EFI.7z](https://drive.google.com/file/d/0B-o-S1Ld1ZTiZTRwc3dUR3BZam8/view?usp=sharing)

**Comment by steve6375** [comment] 2016-09-20 13:14
New EFI.7z still has same issue.
Do you use the --pubkey parameter? where do you get key file from?
P.S. I can now make efi file without getting the 'grub-efi-secure-boot' not found error - I was using MBR version of Mint, I installed Ubuntu EFI in new UEFI VM on VBox and now I don't get the error when I run clonezilla!

**Comment by nguyentumine** [comment] 2016-09-20 13:25
No, I don't use the public key. Please let me know when you succeed, thanks!

**Comment by nguyentumine** [comment] 2016-10-28 07:16
Hi,

Please help me check **Shimx64.efi**. I took the files from Ubuntu and I hope it will work. I will mark this version is stable if it is improved.

Legacy BIOS mode is also supported on the hard disk in GPT style.

Thank for your time.

**Comment by steve6375** [comment] 2016-10-30 09:54
When you boot in Secure Boot mode, grub2 commands like loopback, linux etc.
are not allowed.
Also scripting does not work correctly due to regular expressions modules,
etc. will not load.
So all you can do is load a .efi file which is also signed for secure boot
(e.g. memtest86).
S

**Comment by nguyentumine** [comment] 2016-10-30 10:16
Thank you, almost modules has been embedded in the file **grubx64.efi**, it is hard to understand. so **shimx64.efi** & **grubx64.efi** provided in Ubuntu will not work for you.

I think it depends on each machine that will be different results. As my friend's computer, it accesses the **Mod Manager**.

**Comment by steve6375** [comment] 2016-10-30 11:01
If I replace bootx64.efi with shimx64.efi and then use MokManager, then it
will boot OK.

Why don't you make AIO Boot with  bootx64.efi=shimx64.efi ??? Then it will
work for EFI and Secure-EFI ?

Steve

**Comment by nguyentumine** [comment] 2016-10-30 11:20
Is it work for you? **Grubx64.efi** lacks NTFS module, I don't know how to compile it.

**Comment by steve6375** [comment] 2016-10-30 11:22
I use FAT32 partition for test
NTFS module is not signed so will not work in Secure Boot?
S

**Comment by nguyentumine** [comment] 2016-10-30 11:26
If you can't use the *insmod* command to load then Yes, it will not work.

**Comment by steve6375** [comment] 2016-10-30 11:31
grub> insmod ntfs
loi: Secure Boot forbids loading module from
(hd0,msdos1)/AIO/grub/x86_64-efi/ntfs.mod

:-(

**Comment by nguyentumine** [comment] 2016-10-30 11:37
Yes, I don't know how to compile it. maybe we need to ask Canonical how do they do it :+1: my English is not good, help me get the answers [here](https://lists.gnu.org/archive/html/help-grub/) please.

**Comment by nguyentumine** [comment] 2016-11-02 03:02
I've embedded NTFS module, hope it works, help me test it, thank you.
[grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiSVNDMk11enFwSm8/view?usp=sharing)

**Comment by steve6375** [comment] 2016-11-02 11:00
I think you would need to ask Ubuntu folks.
Steve

**Comment by nguyentumine** [comment] 2016-11-02 11:03
I've embedded NTFS module [grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiSVNDMk11enFwSm8/view?usp=sharing)

**Comment by steve6375** [comment] 2016-11-02 15:11
When I used the MokManager on my Lenovo IdeaPad 300 it worked fine.
When I used it on my Asus Z87A PC, as soon as I selected 'Enroll hash from
disk' option it crashed (hang - no response from keyboard or ctrl-alt-del)!
I tried using USB Flash drive and USB HDD, and both crashed in same way.
So some incompatibility in MokManager.efi and Z87 BIOS ????
Where did you get MokManager from? Is there a different version?


Steve

**Comment by nguyentumine** [comment] 2016-11-02 21:08
Got it from Ubuntu, Try replace MokManager to the previous version.
I think it depends on each machine that will be different results.

**Comment by nguyentumine** [comment] 2016-11-05 23:01
I have compiled [grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiNm4xZFpjR2llY1U/view?usp=sharing) that is going to use the prefix is **/EFI/BOOT**. Just create a file **grub.cfg** there and redirect it to a different configuration.
Hope it helps for all those who want to use the Shim and MOK to pass the Secure Boot.

**Comment by steve6375** [comment] 2016-11-06 00:10
Thanks!

**Comment by steve6375** [comment] 2016-11-06 00:19
I just tested this version and it is behaving differently.
e.g. if I run cpuid it says it is not allowed to load the module. I cannot
run Ubuntu or clonezilla, etc.
The previous version (that uses AIO\grub\grub.cfg) was OK.
Also, the version in AIO 0.9 has a problem too.
The version I used in the grub2 .imgPTN file was the NTFS version you sent
me.
Steve

**Comment by steve6375** [comment] 2016-11-06 00:23
---------------------------
Checksum information
---------------------------
Name: grubx64.efi
Size: 1364480 bytes (1 MB)
SHA1: 0FD907C43D3AF1418C8FD48894E49D991E93E312
This is the version that works OK.  AIO cfg


---------------------------
Checksum information
---------------------------
Name: grubx64.efiNEW
Size: 1361920 bytes (1 MB)
SHA1: F6AE1E590869AB93C1E184048F1074B34B624B11
---------------------------
This is latest \boot\grub\grub.cfg version which has a problem.
---------------------------

**Comment by nguyentumine** [comment] 2016-11-06 00:42
Sorry, I've compiled that module **CPUID** is missing. Thanks for your time.
New version with **cpuid**: [grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiMG5IR3RZRWNGUFE/view?usp=sharing)

**Comment by nguyentumine** [comment] 2016-11-06 00:59
Why don't you use the **$grub_cpu** variable to determine the architecture that the user is using?

**Comment by steve6375** [comment] 2016-11-06 09:21
Thanks, that is better, but it doesn't boot ubunto etc because the linuxefi
module is giving a secure boot error.

The modules that will not load are:
*ls*
*read*
*all-video*
*bsd*
*linuxefi*

The AIO NTFS version worked OK and all modules were loaded (but it did give
the message 'error: symbol 'grub_efi_allocate_pages_max' not found on
booting for a split second)

cheers
Steve

**Comment by nguyentumine** [comment] 2016-11-06 09:29
**linuxefi** is missing, try replace **linuxefi** with **linux**, is it work?

**Comment by nguyentumine** [comment] 2016-11-06 10:04
New version, help me test it please, embedded modules as you need [grubx64.efi](https://drive.google.com/file/d/0B-o-S1Ld1ZTiMG5IR3RZRWNGUFE/view?usp=sharing)

**Comment by steve6375** [comment] 2016-11-06 10:36
Looks good!  :-)

I will let you know if I find any more problems.

Thanks!
Steve

**Closed** 2016-12-07 06:22 UTC
